### ISSUE TITLE
Where is the config file?

### ISSUE THREAD

**Issue by TheBeaconCrafter** [paulgoio/searxng#16]
So basically, I'm new to docker and Searx and I feel really dumb for asking such a noob question but where ist the config file located? I know that searx has a config file, but I am not able to find it. Can someone help me please?

**Comment by mrpaulblack** [comment]
Hi @TheBeaconCrafter ,
the config file is in [repo root]/searx/settings.yml

If you use my Fork or SearXNG its located in `/usr/local/searxng/searx/settings.yml`. You can modify my docker-compose.yml like this to mount your own `settings.yml file from the same directory where the docker-compose.yml file lives:

```yaml
version: '3.7'

services:
  searxng:
    image: paulgoio/searxng:production
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./settings.yml:/usr/local/searxng/searx/settings.yml
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    environment:
      - FILTRON=true
      - IMAGE_PROXY=true
      - DOMAIN=[insert your domain here]
      - NAME=[insert the name of your instance here; can be anything]
      - CONTACT=https://about.paulgo.io/#about
      - ISSUE_URL=https://github.com/paulgoio/searxng/issues
      - GIT_URL=https://github.com/paulgoio/searxng
      - GIT_BRANCH=main
```

Copy the settings.yml file from here: https://github.com/searxng/searxng/blob/master/searx/settings.yml into the same directory where your `docker-compose.yml` is located and change the settings you want to adjust (Some settings like the name of the instance and the git url are controlled by environment variables; you can read about them in the readme of this repo).

After that just start your instance with `docker-compose up -d` and you should have a running instance at `https://[the ip of your server or locahost if on the same PC]:8080`

Hope this helps; Feel free to join our Matrix Group, if you have more questions about setting up SearXNG :+1:

Matrix: [#searxng:matrix.org](https://matrix.to/#/#searxng:matrix.org)

or

IRC: [#searxng on libera.chat which is bridged to Matrix.](https://web.libera.chat/?channel=#searxng)
