### ISSUE TITLE
Building ARM images

### ISSUE THREAD

**Issue by extremelyonline** [paulgoio/searxng#56]
Hi Paulgo, 

Sorry to bother you, may I ask if you would consider building ARM images in the Gitlab runner? It will prolong the build time tho. Thank you so much

**Comment by mrpaulblack** [comment]
Hi,
This repo is just a mirror of my gitlab instance, where I am actually tracking my source code changes... I am also using a gitlab runner to build images: https://paulgo.dev/infra/paulgoio/searxng/-/pipelines .

I do not plan to set up this up, so it works with arm, since I am not using arm for any deployments. Hope you understand.

If you know how to set up the GitLab runner, so it supports building for arm, feel free to open a PR in this mirror tho. I would gladly add the changes, if anybody wants to do the configuration :+1: 

This is my current runner setup with docker-compose on an x86_64 virtual machine running alpine:
```yaml
version: '3'

services:
  gitlab-runner-paulgodev:
    image: registry.gitlab.com/gitlab-org/gitlab-runner:alpine
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./runner-paulgodev.toml:/etc/gitlab-runner/config.toml
```

You can find my templates for the gitlab ci that builds the paulgoio SearXNG images here: https://paulgo.dev/infra/templates

I will keep this ticket open for others to see :smile:
